run:
        gcc Mohammed.c -o program && ./program
clean:
         rm pragram .Mohammed.c.swp
push: commit
        git push
commit: add
        git commit -m "$(MSG)"
add:
        git add .
debug:
        printf $(MSC)
