run:
	gcc Mohammed.c -o program && ./program

clean:
	 rm program

pull:fetch
	git pull

fetch:
	git fetch

push:commit
	git push

commit:add
	git commit -m "$(MSG)"

add:
	git add .

debug:
	printf $(MSC)
